# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a06d4e77140c886f8084bc69493ac2331da9c0977c652510908efe338f75844ea9a013273eed57de78276edcf477998aa6180e8443a0b6e766edcf2dcc0f625

test:
  secret_key_base: 995e01eb88271d7537114cd283984159ed7b0efe7b2151ac8d203bf269dddedaa806d7fc1ae2a05eafa249aaaef3472140d31ef42a601493cb1b8958856a84e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
